// Generated by CIRCT firtool-1.62.1
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

module IF(	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
  input         clock,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
                reset,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
                io_halt,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
                io_jumpen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
  input  [31:0] io_jump,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
  output [31:0] io_pcn,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
                io_pc	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
);

  reg  [31:0] pc;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:128:19]
  wire [31:0] _io_pcn_T = pc + 32'h4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:128:19, :139:16]
  always @(posedge clock) begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
    if (reset)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
      pc <= 32'h80000000;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:128:19]
    else if (io_halt) begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
    end
    else if (io_jumpen)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
      pc <= io_jump;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:128:19]
    else	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:121:14]
      pc <= _io_pcn_T;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:128:19, :139:16]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
    initial begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
        `INIT_RANDOM_PROLOG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
        pc = _RANDOM[/*Zero width*/ 1'b0];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7, :128:19]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
      `FIRRTL_AFTER_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_pcn = _io_pcn_T;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7, :139:16]
  assign io_pc = pc;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:120:7, :128:19]
endmodule

// external module EBreak

module ID(	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
  input         clock,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
                reset,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
  input  [31:0] io_inst,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  input         io_wb_en,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  input  [4:0]  io_wb_rd,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  input  [31:0] io_wb_data,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  output [31:0] io_rs1,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_rs2,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_imm,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  output        io_immen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  output [4:0]  io_rd_addr,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
  output        io_halt,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_jumpen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_memBen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_memRen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_memWen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
                io_regWen	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:194:14]
);

  wire [9:0]  _GEN = {io_inst[14:12], io_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_1 = _GEN == 10'h103;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_3 = _GEN == 10'h203;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_5 = _GEN == 10'h123;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_7 = _GEN == 10'h23;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [16:0] _GEN_0 = {io_inst[31:25], io_inst[14:12], io_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_9 = _GEN_0 == 17'h33;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_11 = _GEN == 10'h13;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_31 = _GEN == 10'h67;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _decoded_T_15 = io_inst[6:0] == 7'h37;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _GEN_1 = _decoded_T_5 | _decoded_T_7;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_2 = _decoded_T_1 | _decoded_T_3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [1:0]  decoded_0 =
    _GEN_2
      ? 2'h1
      : _GEN_1
          ? 2'h2
          : _decoded_T_9
              ? 2'h0
              : _decoded_T_11 | _decoded_T_31 ? 2'h1 : {2{_decoded_T_15}};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [2:0]  decoded_4 =
    _decoded_T_1
      ? 3'h1
      : _decoded_T_3
          ? 3'h2
          : _decoded_T_5
              ? 3'h3
              : _decoded_T_7
                  ? 3'h4
                  : _decoded_T_9 | _decoded_T_11 | _decoded_T_31 | _decoded_T_15
                      ? 3'h0
                      : 3'h3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  reg  [31:0] regfile_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_3;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_5;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_6;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_7;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_8;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_9;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_10;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_11;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_12;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_13;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_14;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_15;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_16;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_17;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_18;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_19;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_20;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_21;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_22;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_23;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_24;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_25;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_26;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_27;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_28;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_29;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_30;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] regfile_31;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
  reg  [31:0] casez_tmp;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:257:16]
  always_comb begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:257:16]
    casez (io_inst[19:15])	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:248:23, :257:16]
      5'b00000:
        casez_tmp = regfile_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00001:
        casez_tmp = regfile_1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00010:
        casez_tmp = regfile_2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00011:
        casez_tmp = regfile_3;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00100:
        casez_tmp = regfile_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00101:
        casez_tmp = regfile_5;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00110:
        casez_tmp = regfile_6;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00111:
        casez_tmp = regfile_7;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01000:
        casez_tmp = regfile_8;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01001:
        casez_tmp = regfile_9;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01010:
        casez_tmp = regfile_10;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01011:
        casez_tmp = regfile_11;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01100:
        casez_tmp = regfile_12;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01101:
        casez_tmp = regfile_13;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01110:
        casez_tmp = regfile_14;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01111:
        casez_tmp = regfile_15;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10000:
        casez_tmp = regfile_16;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10001:
        casez_tmp = regfile_17;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10010:
        casez_tmp = regfile_18;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10011:
        casez_tmp = regfile_19;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10100:
        casez_tmp = regfile_20;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10101:
        casez_tmp = regfile_21;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10110:
        casez_tmp = regfile_22;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10111:
        casez_tmp = regfile_23;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11000:
        casez_tmp = regfile_24;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11001:
        casez_tmp = regfile_25;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11010:
        casez_tmp = regfile_26;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11011:
        casez_tmp = regfile_27;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11100:
        casez_tmp = regfile_28;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11101:
        casez_tmp = regfile_29;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11110:
        casez_tmp = regfile_30;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      default:
        casez_tmp = regfile_31;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
    endcase	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:248:23, :257:16]
  end // always_comb
  reg  [31:0] casez_tmp_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:258:10]
  always_comb begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:257:16]
    casez (io_inst[24:20])	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:249:23, :257:16]
      5'b00000:
        casez_tmp_0 = regfile_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00001:
        casez_tmp_0 = regfile_1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00010:
        casez_tmp_0 = regfile_2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00011:
        casez_tmp_0 = regfile_3;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00100:
        casez_tmp_0 = regfile_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00101:
        casez_tmp_0 = regfile_5;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00110:
        casez_tmp_0 = regfile_6;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b00111:
        casez_tmp_0 = regfile_7;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01000:
        casez_tmp_0 = regfile_8;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01001:
        casez_tmp_0 = regfile_9;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01010:
        casez_tmp_0 = regfile_10;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01011:
        casez_tmp_0 = regfile_11;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01100:
        casez_tmp_0 = regfile_12;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01101:
        casez_tmp_0 = regfile_13;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01110:
        casez_tmp_0 = regfile_14;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b01111:
        casez_tmp_0 = regfile_15;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10000:
        casez_tmp_0 = regfile_16;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10001:
        casez_tmp_0 = regfile_17;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10010:
        casez_tmp_0 = regfile_18;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10011:
        casez_tmp_0 = regfile_19;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10100:
        casez_tmp_0 = regfile_20;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10101:
        casez_tmp_0 = regfile_21;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10110:
        casez_tmp_0 = regfile_22;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b10111:
        casez_tmp_0 = regfile_23;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11000:
        casez_tmp_0 = regfile_24;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11001:
        casez_tmp_0 = regfile_25;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11010:
        casez_tmp_0 = regfile_26;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11011:
        casez_tmp_0 = regfile_27;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11100:
        casez_tmp_0 = regfile_28;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11101:
        casez_tmp_0 = regfile_29;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      5'b11110:
        casez_tmp_0 = regfile_30;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
      default:
        casez_tmp_0 = regfile_31;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :257:16]
    endcase	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:249:23, :257:16]
  end // always_comb
  reg  [31:0] casez_tmp_1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:259:35]
  always_comb begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:259:35]
    casez (decoded_0)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:259:35, src/main/scala/chisel3/util/Lookup.scala:34:39]
      2'b00:
        casez_tmp_1 = 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:32, :259:35]
      2'b01:
        casez_tmp_1 = {{20{io_inst[31]}}, io_inst[31:20]};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:113:{8,13,26}, :252:27, :259:35]
      2'b10:
        casez_tmp_1 = {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:113:{8,13,26}, :247:23, :253:31, :259:35]
      default:
        casez_tmp_1 = {io_inst[31:12], 12'h0};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:254:{22,30}, :259:35]
    endcase	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:259:35, src/main/scala/chisel3/util/Lookup.scala:34:39]
  end // always_comb
  wire        _io_memRen_T_4 = decoded_4 == 3'h2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:274:42, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire        _io_memWen_T_4 = decoded_4 == 3'h4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:274:65, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire        _is_unimpl_T_22 =
    _GEN == 10'h103 | _GEN == 10'h203 | _GEN == 10'h123 | _GEN == 10'h23
    | _GEN_0 == 17'h33 | _GEN == 10'h13 | _GEN == 10'h67 | io_inst[6:0] == 7'h37;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:289:{50,69}, src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _GEN_3 = io_wb_en & (|io_wb_rd);	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:278:{18,30}]
  always @(posedge clock) begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
    if (reset) begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      regfile_0 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_1 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_2 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_3 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_4 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_5 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_6 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_7 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_8 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_9 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_10 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_11 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_12 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_13 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_14 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_15 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_16 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_17 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_18 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_19 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_20 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_21 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_22 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_23 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_24 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_25 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_26 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_27 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_28 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_29 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_30 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
      regfile_31 <= 32'h0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:{24,32}]
    end
    else begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      if (_GEN_3 & ~(|io_wb_rd))	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :278:{18,30,39}, :279:23]
        regfile_0 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_1 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h2)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_2 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h3)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_3 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h4)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_4 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h5)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_5 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h6)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_6 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h7)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_7 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h8)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_8 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h9)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_9 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hA)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_10 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hB)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_11 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hC)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_12 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hD)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_13 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hE)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_14 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'hF)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_15 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h10)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_16 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h11)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_17 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h12)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_18 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h13)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_19 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h14)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_20 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h15)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_21 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h16)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_22 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h17)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_23 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h18)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_24 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h19)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_25 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1A)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_26 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1B)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_27 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1C)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_28 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1D)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_29 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & io_wb_rd == 5'h1E)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24, :278:{18,39}, :279:23]
        regfile_30 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
      if (_GEN_3 & (&io_wb_rd))	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24, :278:{18,39}, :279:23]
        regfile_31 <= io_wb_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:243:24]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      `FIRRTL_BEFORE_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:31];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
    initial begin	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
        `INIT_RANDOM_PROLOG_	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM[i[4:0]] = `RANDOM;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
        end	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
        regfile_0 = _RANDOM[5'h0];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_1 = _RANDOM[5'h1];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_2 = _RANDOM[5'h2];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_3 = _RANDOM[5'h3];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_4 = _RANDOM[5'h4];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_5 = _RANDOM[5'h5];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_6 = _RANDOM[5'h6];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_7 = _RANDOM[5'h7];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_8 = _RANDOM[5'h8];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_9 = _RANDOM[5'h9];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_10 = _RANDOM[5'hA];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_11 = _RANDOM[5'hB];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_12 = _RANDOM[5'hC];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_13 = _RANDOM[5'hD];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_14 = _RANDOM[5'hE];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_15 = _RANDOM[5'hF];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_16 = _RANDOM[5'h10];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_17 = _RANDOM[5'h11];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_18 = _RANDOM[5'h12];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_19 = _RANDOM[5'h13];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_20 = _RANDOM[5'h14];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_21 = _RANDOM[5'h15];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_22 = _RANDOM[5'h16];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_23 = _RANDOM[5'h17];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_24 = _RANDOM[5'h18];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_25 = _RANDOM[5'h19];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_26 = _RANDOM[5'h1A];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_27 = _RANDOM[5'h1B];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_28 = _RANDOM[5'h1C];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_29 = _RANDOM[5'h1D];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_30 = _RANDOM[5'h1E];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
        regfile_31 = _RANDOM[5'h1F];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:24]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
      `FIRRTL_AFTER_INITIAL	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  EBreak trap (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:283:20]
    .trap (~reset & ~_is_unimpl_T_22),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:289:{19,69}, :303:{19,33}]
    .code
      (io_inst == 32'h100073
         ? 8'h0
         : io_inst == 32'h0
             ? 8'h1
             : io_inst[6:0] == 7'h73 & io_inst != 32'h100073
                 ? 8'h2
                 : {6'h0, ~_is_unimpl_T_22, 1'h1})	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:32, :274:17, :289:{19,69}, :290:26, :291:28, :292:{28,35,47}, src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/chisel3/util/Mux.scala:126:16]
  );
  assign io_rs1 = io_inst[6:0] == 7'h37 ? 32'h0 : casez_tmp;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :243:32, :257:{16,25}, src/main/scala/chisel3/util/Lookup.scala:31:38]
  assign io_rs2 = casez_tmp_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :258:10]
  assign io_imm = casez_tmp_1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :259:35]
  assign io_immen = |decoded_0;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :264:23, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_rd_addr = io_inst[11:7];	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :247:23]
  assign io_halt = ~reset & ~_is_unimpl_T_22;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :289:{19,69}, :306:{14,28}]
  assign io_jumpen =
    ~(_decoded_T_1 | _decoded_T_3 | _decoded_T_5 | _decoded_T_7 | _decoded_T_9
      | _decoded_T_11) & _decoded_T_31;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_memBen = ~reset & _io_memRen_T_4 | _io_memWen_T_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :274:{17,31,42,54,65}]
  assign io_memRen = ~reset & decoded_4 == 3'h1 | _io_memRen_T_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :274:42, :275:{17,31,42,54}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_memWen = ~reset & decoded_4 == 3'h3 | _io_memWen_T_4;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :274:65, :276:{17,31,42,54}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_regWen = ~reset & (|(_GEN_2 ? 2'h2 : {1'h0, ~_GEN_1}));	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:191:7, :277:{17,31,41}, src/main/scala/chisel3/util/Lookup.scala:34:39]
endmodule

module EX(	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:312:7]
  input  [31:0] io_rs1,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:314:14]
                io_rs2,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:314:14]
                io_imm,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:314:14]
  input         io_immen,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:314:14]
  output [31:0] io_exout	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:314:14]
);

  assign io_exout = io_immen ? io_rs1 + io_imm : io_rs1 + io_rs2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:312:7, :324:18, :326:{12,29}]
endmodule

module MiniRV(	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7]
  input         clock,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7]
                reset,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7]
  output [31:0] io_pc,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  input  [31:0] io_inst,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  output        io_mem_we,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  output [31:0] io_mem_addr,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  output [7:0]  io_mem_mask,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  output [31:0] io_mem_wdata,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
  input  [31:0] io_mem_rdata	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:336:14]
);

  wire [31:0] _exStage_io_exout;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:349:23]
  wire [31:0] _idStage_io_rs1;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire [31:0] _idStage_io_rs2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire [31:0] _idStage_io_imm;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_immen;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire [4:0]  _idStage_io_rd_addr;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_halt;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_jumpen;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_memBen;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_memRen;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire        _idStage_io_regWen;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
  wire [31:0] _ifStage_io_pcn;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:347:23]
  wire [62:0] _io_mem_wdata_T_2 =
    {31'h0, _idStage_io_rs2} << {58'h0, _exStage_io_exout[1:0], 3'h0};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23, :349:23, :372:{38,58,64}]
  wire [31:0] _byte_data_T = io_mem_rdata >> {27'h0, _exStage_io_exout[1:0], 3'h0};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:349:23, :372:{58,64}, :380:33]
  IF ifStage (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:347:23]
    .clock     (clock),
    .reset     (reset),
    .io_halt   (_idStage_io_halt),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_jumpen (_idStage_io_jumpen),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_jump   (_exStage_io_exout),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:349:23]
    .io_pcn    (_ifStage_io_pcn),
    .io_pc     (io_pc)
  );
  ID idStage (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .clock      (clock),
    .reset      (reset),
    .io_inst    (io_inst),
    .io_wb_en   (_idStage_io_regWen),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_wb_rd   (_idStage_io_rd_addr),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_wb_data
      (_idStage_io_memRen
         ? (_idStage_io_memBen
              ? {{24{_byte_data_T[7]}}, _byte_data_T[7:0]}
              : io_mem_rdata)
         : _idStage_io_jumpen ? _ifStage_io_pcn : _exStage_io_exout),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:347:23, :348:23, :349:23, :380:{33,47}, :381:22, :382:{26,31,45}, src/main/scala/chisel3/util/Mux.scala:126:16]
    .io_rs1     (_idStage_io_rs1),
    .io_rs2     (_idStage_io_rs2),
    .io_imm     (_idStage_io_imm),
    .io_immen   (_idStage_io_immen),
    .io_rd_addr (_idStage_io_rd_addr),
    .io_halt    (_idStage_io_halt),
    .io_jumpen  (_idStage_io_jumpen),
    .io_memBen  (_idStage_io_memBen),
    .io_memRen  (_idStage_io_memRen),
    .io_memWen  (io_mem_we),
    .io_regWen  (_idStage_io_regWen)
  );
  EX exStage (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:349:23]
    .io_rs1   (_idStage_io_rs1),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_rs2   (_idStage_io_rs2),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_imm   (_idStage_io_imm),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_immen (_idStage_io_immen),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:348:23]
    .io_exout (_exStage_io_exout)
  );
  assign io_mem_addr = _exStage_io_exout;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7, :349:23]
  assign io_mem_mask = {4'h0, _idStage_io_memBen ? 4'h1 << _exStage_io_exout[1:0] : 4'hF};	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7, :348:23, :349:23, :372:58, :374:{16,22}, :375:27]
  assign io_mem_wdata = _idStage_io_memBen ? _io_mem_wdata_T_2[31:0] : _idStage_io_rs2;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:333:7, :348:23, :371:22, :372:38]
endmodule

// external module ROM_DPI

// external module RAM_DPI

module MiniRVSOC(	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:400:7]
  input         clock,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:400:7]
                reset,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:400:7]
  output [31:0] io_pc,	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:401:14]
                io_inst	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:401:14]
);

  wire [31:0] _ram_rdata;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:408:19]
  wire [31:0] _rom_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:407:19]
  wire [31:0] _cpu_io_pc;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
  wire        _cpu_io_mem_we;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
  wire [31:0] _cpu_io_mem_addr;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
  wire [7:0]  _cpu_io_mem_mask;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
  wire [31:0] _cpu_io_mem_wdata;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
  MiniRV cpu (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .clock        (clock),
    .reset        (reset),
    .io_pc        (_cpu_io_pc),
    .io_inst      (_rom_data),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:407:19]
    .io_mem_we    (_cpu_io_mem_we),
    .io_mem_addr  (_cpu_io_mem_addr),
    .io_mem_mask  (_cpu_io_mem_mask),
    .io_mem_wdata (_cpu_io_mem_wdata),
    .io_mem_rdata (_ram_rdata)	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:408:19]
  );
  ROM_DPI rom (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:407:19]
    .addr (_cpu_io_pc),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .data (_rom_data)
  );
  RAM_DPI ram (	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:408:19]
    .we    (_cpu_io_mem_we),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .addr  (_cpu_io_mem_addr),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .mask  (_cpu_io_mem_mask),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .wdata (_cpu_io_mem_wdata),	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:406:19]
    .rdata (_ram_rdata)
  );
  assign io_pc = _cpu_io_pc;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:400:7, :406:19]
  assign io_inst = _rom_data;	// @[home/moon/ysyx/ysyx/npc/chisel/src/RiscV/MiniRV.scala:400:7, :407:19]
endmodule

